### ISSUE TITLE
Error with local-login

### ISSUE THREAD

**Issue by schersh** [ga-wdi-exercises/project3#74]
Users can currently sign-up for an account w/o error, and the app recognizes if an email is still in use. A user can sign-in with their email and password w/o error within that same session. However, if I open a new browser window or restart the server, the following error occurs when that user tries to sign-in: 

Error: Unknown authentication strategy "local-login"

I'm defining the local-login strategy in the same file as the local-signup strategy, so I don't understand why one seems to be working and the other is not. I also wonder if the user is not being saved correctly to the database, and that is why login only works with the same session as sign-up? 

Here are the relevant functions from my usersController.js 

``` js
function getSignup(request, response) {
    response.render("signup.hbs", { message: request.flash('signupMessage') });
  }

  function postSignup(request, response, next) {
    var signupStrategy = passport.authenticate('local-signup', {
      successRedirect : '/',
      failureRedirect : '/signup',
      failureFlash : true
    });
    return signupStrategy(request, response, next);
  }

  function getLogin(request, response) {
    response.render('login.hbs', { message: request.flash('loginMessage') } );
  }

  function postLogin(request, response, next) {
    var loginProperty = passport.authenticate('local-login', {
      successRedirect : '/',
      failureRedirect : '/login',
      failureFlash : true
    });
    return loginProperty(request, response, next);
  }
```

**Comment by RobertAKARobin** [comment]
I'm going to guess that's because either you have a cookie stored in your browser that your server thinks belongs to a session that no longer exists -- or your server has a session that corresponds to a cookie that no longer exists.

If you sign out, or do something with `req.session.destroy();` in it, that should fix it!

**Comment by RobertAKARobin** [comment]
My hunch stems for this happening to me ALL THE TIME when I was working on Garnet.

**Comment by schersh** [comment]
Ok, thanks - I added req.session.destroy(); to my function getLogout and I can create a user, logout and then log them in again, but if I open a new browser window/restart the server and attempt to login with the same user account, I still get this error: 
Error: Unknown authentication strategy "local-login"
(...)
   at postLogin (/Users/schersh/WDI/projects/Travel_app_project_3/controllers/usersController.js:40:12)

My code at line 40 from my usersController is: 
`return loginProperty(request, response, next);`

**Comment by RobertAKARobin** [comment]
Hm. Can you push your code up to Github so I can try it?

**Comment by schersh** [comment]
Sure, I just pushed it up to the same branch.  I'm also noticing that even when the user is logged in, this code `"/user/{{_id}}"` is not successfully finding their id.

**Comment by schersh** [comment]
although that id issue might be because I was referencing user instead of currentUser.local?

**Comment by RobertAKARobin** [comment]
Could you link to your repo? Sorry, I'm juggling rather a lot of them over here!

**Comment by schersh** [comment]
Sorry  - https://github.com/schersh/Travel_app_project_3/tree/s_user_auth

**Comment by RobertAKARobin** [comment]
How can I tell when I'm signed in? Is there any visual feedback?

**Comment by RobertAKARobin** [comment]
Oh, I meant that if you get that error, try going to the log-out path even if you're not actually logged in. You may have residual session data hanging around that's throwing things off.

**Comment by schersh** [comment]
Once you land on the profile page, you see a message like logged in as {{currentUser.local.email}} but the browser doesn't seem able to grab the id of the logged in user to navigate to that view, so that's why now it just redirects to the home page (which isn't helpful). I added a logged in as {{currentUser.local.email}} to the index.hbs, but it's failing to pull the user's email address (either that or no one is actually logging in but no error is being called). 
I'm not sure I understand your second point - do you mean redirect users to the log-out path before they can log-in?

**Comment by RobertAKARobin** [comment]
Another problem here may be that `express-session` actually only stores one session at a time -- it's not supposed to be used with multiple users in a production environment.

The long-and-short of all of this is I'd say just don't worry about multiple users being on your app for right now. While you're developing, assume that you're going to have only one user at any given point in time, and that they'll the rules.

**Comment by schersh** [comment]
Okay, that's fine if only one person can be logged in at a time, but why aren't they able to log-out and then log-in again?

**Comment by schersh** [comment]
And is my syntax incorrect for trying to get the data of the current user? I can't even get the user to be able to navigate to their profile page or perform any CRUD functions on our database.

**Comment by RobertAKARobin** [comment]
This took a LOT of looking. Believe it or not, the whole problem here is punctuation: `local-login` was technically **inside** `local-signup`. You have this:

``` j
    });

  passport.use('local-login', new LocalStrategy({
    usernameField : 'email',
    passwordField : 'password',
    passReqToCallback : true
  }, function(req, email, password, callback) {
    User.findOne({ 'local.email' :  email }, function(err, user) {
          if (err) {
            return callback(err);
          }

          // If no user is found
          if (!user) {
            return callback(null, false, req.flash('loginMessage', 'No user found.'));
          }
          // Wrong password
          if (!user.validPassword(password)) {
            return callback(null, false, req.flash('loginMessage', 'Oops! Wrong password.'));
          }
          return callback(null, user);
        });
      }));
   }));
```

Replace it with this:

``` js
    });
  }));

  passport.use('local-login', new LocalStrategy({
    usernameField : 'email',
    passwordField : 'password',
    passReqToCallback : true
  }, function(req, email, password, callback) {
    User.findOne({ 'local.email' :  email }, function(err, user) {
          if (err) {
            return callback(err);
          }

          // If no user is found
          if (!user) {
            return callback(null, false, req.flash('loginMessage', 'No user found.'));
          }
          // Wrong password
          if (!user.validPassword(password)) {
            return callback(null, false, req.flash('loginMessage', 'Oops! Wrong password.'));
          }
          return callback(null, user);
        });
      }));
```

**Comment by RobertAKARobin** [comment]
It's been a while so I'm going to close this. Feel free to open a new one!

**Comment by schersh** [comment]
Sorry, I didn't see this earlier because I was working with Erica. Thank you for your help.
